---
title: "Schedule"
output: html_document
---

You can download the notes for the class:

<a class="btn btn-warning" href="pdf/econ-21130-notes.pdf" role="button">Notes by methods</a> <a class="btn btn-success" href="pdf/econ-21130-applied.pdf" role="button">Notes by example</a>
 
## Class schedule

  - Linear models for cross-section (running example will be labor supply) 
    - Clarify concepts such as data, model, identification, estimation and inference <i class="fas fa-check"></i>
    - Study theats to identification  (endogeneity, measurement error, simultaneity)
    - Finite sample gaussian inference <i class="fas fa-check"></i>
    - Asymptotic inference (central limit theorem) <i class="fas fa-check"></i>
    - [Lab <i class="fa fa-external-link" aria-hidden="true"></i>](lab-labor-supply.html) on labor supply  <i class="fas fa-check"></i>
    - Heckman (77)  [paper <i class="fa fa-external-link" aria-hidden="true"></i>](http://www.nber.org/papers/w0172) <i class="fas fa-check"></i>
    - Saez (99) [paper <i class="fa fa-external-link" aria-hidden="true"></i>](https://eml.berkeley.edu/~saez/saezAEJ10bunching.pdf) and [slides <i class="fa fa-download" aria-hidden="true"></i> ](pdf/slides-laborsupply-kink-ug.pdf) <i class="fas fa-check"></i>
    - Blundell, Duncan and Meghir (98) [paper <i class="fa fa-external-link" aria-hidden="true"></i>](https://www.jstor.org/stable/2999575) and [slides <i class="fa fa-download" aria-hidden="true"></i> ](pdf/slides-laborsupply-bdm-ug.pdf)
    - Clustering of standard errors, Cameron and Miller guide [paper <i class="fa fa-external-link" aria-hidden="true"></i>](http://cameron.econ.ucdavis.edu/research/Cameron_Miller_JHR_2015_February.pdf)
    - Thinking about multiple testing
  - Multinomial decisions (we will use transportation and monopolistic competition)
    - Introducing Maximum Likelihood Estimation
    - Estimation of multinomial logit
    - McFadden (74) [paper <i class="fa fa-external-link" aria-hidden="true"></i>](https://www.sciencedirect.com/science/article/pii/0047272774900036)
    - Maximum score estimation, Manski (75) [paper <i class="fa fa-external-link" aria-hidden="true"></i>](https://www.sciencedirect.com/science/article/pii/0304407675900329)
    - [Lab <i class="fa fa-external-link" aria-hidden="true"></i>](lab-labor-supply.html) on discrete choice 
    - Marriage market with Choo and Siow (03) [paper <i class="fa fa-external-link" aria-hidden="true"></i>](http://homes.chass.utoronto.ca/~siow/papers/who_marries_whom.pdf)
    - Boostrap
  - Unobserved heterogeneity
    - Revisit multinomial problem and IIA 
    - Random effect model and EM-algorithm
    - Introduction to Variational Auto Encoders [VAE <i class="fa fa-external-link" aria-hidden="true"></i>](https://arxiv.org/abs/1312.6114)
  - Topics in non-parametrics and high-dimensional econometrics
    - model complexity and bias/variance trade-off
    - many regressors (application to network of peers)
    - non parametric regression
  - Measuring sorting in the labor market
    - incidental parameter problems
    - Fixed-effect approach, bias correction
    - Group fixed effect approach
  - Dynamic programing 
    - Introducing Bellman equations (through cake eating problem)
    - Study the estimation of dynamic programing 
    - [Lab <i class="fa fa-external-link" aria-hidden="true"></i>](lab-labor-supply.html) on dynamic discrete choice 
    - Rust (74) [paper <i class="fa fa-external-link" aria-hidden="true"></i>](http://people.hss.caltech.edu/~mshum/stats/rust.pdf)

## Homeworks

You can submit your homework either as solo or as a group of two. To communicate about your homework, create a channel in our slack group with a name starting with `grp_` and then with the initials of the members of your group. For instance the TA (Arjun) and myself (Thibaut) would be `grp_at`. Then please add Arjun and myself as members of that group. You can make your group private if you don't want other students to see your homework. Submit the analytical parts directly to this slack group.

<!-- To submit your answers to computational homeworks. Please create a `git` repository (you can make it private), and add the RA and myself as contributor (in the case of private), or just share the URL with us if you choose to make the repo public. You can create your repository on [github](http://github.com) or [bitbucket](htpp://bitbucket.org), your choice! -->

 - <span class="label label-warning">new</span> [Homework 1](pdf/hw1_f19.pdf) (analytical) due date is Tuesday Oct 15th . 
 - [Homework 2](hw-lsupply.html) (computer) due on Sunday October 27th at midnight. 
 - [Homework 3](pdf/hw3-fall19.pdf) (analytical) due Tuesday Nov 5th at 11:59 PM.
 - [Homework 4](hw-inference.html) (computer) due date TBD. 
 - [Homework 5](hw-hetero.html) (computer) due date TBD. 
 
## End of class project

 - The project can be done in groups of three. The goal is for you to take an economic or policy question and to develop a DGP for that question as well as a method adpated to answering that question given data. The project should highlight the potential pitfalls of given methods. 
 - 1 page proposal is due on week 8, Thrudsay nov 21st. This should include a question and a DGP.
 - finall submission of the project will be after finals.

## Midterm

 - The <span class="label label-warning">midterm</span> will in week 7, on Thursday November 14th.
 - I will be away during week 4 (Oct 22nd and 24th).

## Grading scheme

Overall grade will be 1/3 homeworks, 1/3 midterm, 1/3 project.

## Books

These are some books that can be helpful to dig into more details of the topics covered in class. These books are __not required__ for the class.

 - [Microeconometrics: Methods and Applications: A. Colin Cameron, Pravin K. Trivedi](https://www.amazon.com/Microeconometrics-Methods-Applications-Colin-Cameron/dp/0521848059)
 - [Econometric Theory and Methods, Davidson and MacKinnon](https://www.amazon.com/Econometric-Theory-Methods-Russell-Davidson/dp/0195123727)
 - [An Introduction to Statistical Learning: with Applications in R, Gareth James, Daniela Witten, Trevor Hastie, Robert Tibshirani](https://www.amazon.com/Introduction-Statistical-Learning-Applications-Statistics/dp/1461471370)
 - [All of Statistics: A Concise Course in Statistical Inference, Larry Wasserman](https://www.amazon.com/All-Statistics-Statistical-Inference-Springer/dp/0387402721/ref=sr_1_1?keywords=all+of+statistics&qid=1571320533&s=books&sr=1-1)
